const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const pages = {
  home: read('index.html'),
  work: read('work/index.html'),
  lost: read('404.html')
};
const source = [read('script.js'), read('flash.js'), read('styles.css')].join('\n');
const failures = [];
const check = (label, pass, detail = '') => {
  console.log(`${pass ? 'ok  ' : 'FAIL'} ${label}${detail ? ` — ${detail}` : ''}`);
  if (!pass) failures.push(label);
};

const versionMatches = Object.values(pages).flatMap(page =>
  [...page.matchAll(/(?:\.css|\.js|favicon\.svg)\?v=(\d+)/g)].map(match => match[1]));
check('assets use one cache version', versionMatches.length > 6 && new Set(versionMatches).size === 1,
  [...new Set(versionMatches)].join(', '));

for (const [name, html] of Object.entries(pages)) {
  const local = [...html.matchAll(/(?:src|href)="([^"#]+)"/g)]
    .map(match => match[1].split('?')[0])
    .filter(ref => !/^(?:https?:|mailto:|javascript:)/.test(ref) && !ref.endsWith('/'));
  const missing = local.filter(ref => {
    const clean = ref.replace(/^\/+/, '');
    const from = name === 'work'
      ? (ref.startsWith('../') ? ref.slice(3) : path.join('work', clean))
      : clean;
    return !fs.existsSync(path.join(root, from));
  });
  check(`${name} has no missing local assets`, !missing.length, [...new Set(missing)].join(', '));

  const undimensioned = [...html.matchAll(/<img\b[^>]*>/g)]
    .map(match => match[0]).filter(tag => !/\bwidth="\d+"/.test(tag) || !/\bheight="\d+"/.test(tag));
  check(`${name} images reserve their space`, !undimensioned.length, String(undimensioned.length));
}

const humanScan = Object.values(pages).join('\n').toLowerCase();
const tells = [
  'chatgpt', 'openai', 'claude', 'codex', 'ai-generated', 'generated by',
  'lorem ipsum', 'placeholder', 'built for visitors', 'seamless experience', 'cutting-edge'
].filter(term => humanScan.includes(term));
check('visible copy contains no generator or template tells', !tells.length, tells.join(', '));

check('Yeoui is a drawing, not an input surface',
  !pages.home.includes('staff-hit') && !pages.home.includes('staff-grip') &&
  !source.includes('staffGrip') && !source.includes("querySelector('.staff')") &&
  !source.includes('.swing-ghost'));

const traced = [...pages.home.matchAll(/<p class="traced-does">([\s\S]*?)<\/p>/g)]
  .map(match => match[1].replace(/<[^>]+>/g, '').trim());
check('the source notes cover seven distinct objects', traced.length === 7, String(traced.length));
check('the source notes avoid the old factual error',
  !pages.home.includes('2.5 times the damage') && pages.home.includes('power of 2.5'));
check('the work case uses a concrete heading',
  pages.work.includes('A public site the team can keep current.') && !pages.work.includes('Built for visitors'));

for (const [name, html] of Object.entries(pages)) {
  const unsafe = [...html.matchAll(/<a\b[^>]*target="_blank"[^>]*>/g)]
    .map(match => match[0]).filter(tag => !/rel="[^"]*noopener/.test(tag));
  check(`${name} opens external tabs safely`, !unsafe.length, String(unsafe.length));
}

const allIds = new Set(Object.values(pages).flatMap(html =>
  [...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1])));
const requestedIds = [...source.matchAll(/getElementById\('([^']+)'\)/g)].map(match => match[1]);
const absentIds = [...new Set(requestedIds)].filter(id => !allIds.has(id));
check('JavaScript only requests existing elements', !absentIds.length, absentIds.join(', '));

check('the nested 404 uses root-absolute assets',
  !/(?:href|src)="(?:\.\.\/|\.\/)(?:fonts|styles|flash|favicon)/.test(pages.lost));

const suites = fs.readdirSync(__dirname).filter(file => file.endsWith('.test.js')).sort();
check('the test inventory stays deliberately small',
  JSON.stringify(suites) === JSON.stringify(['smoke.test.js', 'source.test.js', 'upstream.test.js']),
  suites.join(', '));

console.log(failures.length ? `\n${failures.length} source check(s) failed` : '\nsource checks pass');
process.exit(failures.length ? 1 : 0);
